In [113]:
import pandas as pd
import xml.etree.ElementTree as ET

# Aufgabe 2: Semistrukturierte Daten

### JSON einlesen und normalisieren

In [114]:
file_path = 'data/semistrukturiert/Personen.json'

df = pd.read_json(file_path, encoding='utf-8')
df = pd.json_normalize(df['personen'])

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   name     10 non-null     object
 1   vorname  10 non-null     object
 2   alter    9 non-null      object
dtypes: object(3)
memory usage: 368.0+ bytes

In [115]:
df.describe()

          name vorname  alter
count       10      10      9
unique      10      10      9
top     Müller    Anna     28
freq         1       1      1

#### Inkorrekte Werte in Alter-Spalte finden

In [116]:
print(f"Datentyp Spalte Alter: {df['alter'].dtype}")
df

Datentyp Spalte Alter: object

       name vorname alter
0    Müller    Anna    28
1   Schmidt   Lukas    34
2     Weber  Sophie    22
3   Fischer    Leon    30
4    Wagner   Marie   NaN
5    Becker   Jonas    40
6  Hoffmann   Laura    31
7   Schäfer    Paul    29
8      Koch    Emma    24
9     Bauer   Felix    35

In [117]:
# Median berechnen (vorher sicherstellen, dass numerisch)
df['alter'] = pd.to_numeric(df['alter'], errors='coerce')
median_alter = df['alter'].median()
print(f"Median Alter: {median_alter}")

# Variante 1: Zuordnung ohne inplace (empfohlen)
df['alter'] = df['alter'].fillna(median_alter)

# Alternative Variante 2: Auf DataFrame-Ebene inplace
# df.fillna({'alter': median_alter}, inplace=True)

print(df)
print(f"Datentyp Spalte Alter: {df['alter'].dtype}")

Median Alter: 30.0
       name vorname  alter
0    Müller    Anna   28.0
1   Schmidt   Lukas   34.0
2     Weber  Sophie   22.0
3   Fischer    Leon   30.0
4    Wagner   Marie   30.0
5    Becker   Jonas   40.0
6  Hoffmann   Laura   31.0
7   Schäfer    Paul   29.0
8      Koch    Emma   24.0
9     Bauer   Felix   35.0
Datentyp Spalte Alter: float64

### XML einlesen und normalisieren

In [118]:
file_path = 'data/semistrukturiert/Personen.xml'

tree = ET.parse(file_path)
root = tree.getroot()

data = []
for person in root.findall('person'):
    eintrag = {}
    for attribute in person:
        eintrag[attribute.tag] = attribute.text
    data.append(eintrag)
df_xml = pd.DataFrame(data)

df_xml.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   name     10 non-null     object
 1   vorname  10 non-null     object
 2   alter    10 non-null     object
dtypes: object(3)
memory usage: 368.0+ bytes